### ISSUE TITLE
install: do not remove non empty directories in the delete task

### ISSUE THREAD

**Issue by aoloe** [Rapiiidooo/Calendar-Wizard#3]
just delete the specific files you have installed. and maybe the directory if it's empty.

but i would not distribute a "delete" script that is not heavily tested on multiple configuration (and it's proven that i cannot do harm)

**Comment by Rapiiidooo** [comment]
I know what you mean, and I think I should just get away the install.sh ... (I wanted to be usefull but I think it will create more problem than resolve ^^')

**Comment by Rapiiidooo** [comment]
I decided to remove install.sh
Thanks for your time @aoloe
